### PR TITLE
Classic

### PR DESCRIPTION
**Pull request by aixiu**
Localization Configuration & version number

### CODE REVIEW

**Comment by Nevcairiel** [comment]
No idea what this is supposed to be, but Inventorian already has classic support.

**Comment by aixiu** [comment]
@Nevcairiel Localization of Chinese and Chinese Traditional Styles

**Comment by Nevcairiel** [comment]
Localization should be provided on the website, it'll then automatically be included in the next update:
https://www.wowace.com/projects/inventorian/localization

**Comment by aixiu** [comment]
@Nevcairiel OK，thx.

**Pull request closed without merging**
